name: PHP Composer

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

permissions:
    contents: read

jobs:
    test:
        name: Run tests on PHP ${{ matrix.php_version }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php_version:
                    - 8.1
                    - 8.2

        steps:
            -   uses: actions/checkout@v3

            -   name: Validate composer.json and composer.lock
                run: composer validate --strict

            -   name: Cache Composer packages
                id: composer-cache
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-php${{ matrix.php_version }}-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php${{ matrix.php_version }}-

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress

            -   name: PHPUnit Tests
                uses: php-actions/phpunit@v3
                env:
                    XDEBUG_MODE: coverage
                with:
                    configuration: phpunit.xml
                    php_extensions: xdebug memcached
                    args: tests --coverage-clover ./coverage.xml

            -   name: Upload coverage reports to Codecov
                uses: codecov/codecov-action@v3
                env:
                    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
